### ISSUE TITLE
【后台】取消预定失效

### ISSUE THREAD

**Issue by esther1414** [davidgrubby/dlife-backoffice#1]
在用户信息“ta的预定”下，选取某一活动点击“取消”后，活动状态未改变，仍为“活动进行中”，再次点击“取消/完成”则提示“操作失败”，且该时间段课程无法再次被预定，但课程reserve数量已减少 （测试数据：学员 ID236，预定编号 326）

**Comment by davidgrubby** [comment]
修改了可以取消的状态判断，增加了事务处理
